export './profile_screen/profile_view.dart';
export './auth_screen/login_view.dart';
export './auth_screen/on_boarding_view.dart';
export './auth_screen/sign_up_view.dart';
export './auth_screen/splash_sceen.dart';
export './chat_screen/chat_screen.dart';
export './profile_screen/profile_view.dart';
export './search_screen/search_screen.dart';
export './dashboard.dart';
