# runtime: php73 # Replace with php74 to use PHP 7.4

# runtime_config:
#   document_root:

# handlers:
# # Serve a directory as a static resource.
# - url: /stylesheets
#   static_dir: stylesheets


# # Serve images as static resources.
# - url: /(.+\.(gif|png|jpg))$
#   static_files: \1
#   upload: .+\.(gif|png|jpg)$

# # Serve your app through a front controller at index.php or public/index.php.
# - url: .*
#   script: auto

# entrypoint:
#   serve handler.php

# env_variables:
#   APP_KEY: base64:7vQo+Ys4cQis8qv891mqp/45QltheK5aqmlTtycUGNc=
#   CACHE_DRIVER: database
#   SESSION_DRIVER: database
#   DB_USERNAME: root
#   DB_DATABASE: fitness
#   DB_PASSWORD: rajesh2017
#   DB_SOCKET: /cloudsql/swift-area-324611:asia-south1:fitness1

